// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmukhcosthdzibpcdvcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdWtoY29zdGhkemlicGNkdmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5MjUyNTksImV4cCI6MjA4MzUwMTI1OX0._n4w5jwNNynYXE7MyaW0xShVnEpqrHM-hIokO3FiRPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});